name: Build and Upload APK to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # Cache dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/*.gradle') }}

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Decode and save keystore
      - name: Decode and Save Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/my-release-key.jks

      # Build APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=android/app/my-release-key.jks \
                                     -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
                                     -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
                                     -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      # Upload APK to S3
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: react-native-apk-storage
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: android/app/build/outputs/apk/release
